// Generated by scripts/update-model-pricing.mjs from https://models.dev/api.json.
// Do not edit manually.

export interface ModelPricing {
  inputPrice: number;
  outputPrice: number;
  cacheReadPrice?: number;
  cacheWritePrice?: number;
  tierThreshold?: number;
  inputPriceHigh?: number;
  outputPriceHigh?: number;
  cacheReadPriceHigh?: number;
  cacheWritePriceHigh?: number;
}

export const geminiModelPricing = {
  "deep-research-max-preview-04-2026": {"inputPrice":2,"outputPrice":12,"cacheReadPrice":0.2,"tierThreshold":200000,"inputPriceHigh":4,"outputPriceHigh":18,"cacheReadPriceHigh":0.4},
  "deep-research-preview-04-2026": {"inputPrice":2,"outputPrice":12,"cacheReadPrice":0.2,"tierThreshold":200000,"inputPriceHigh":4,"outputPriceHigh":18,"cacheReadPriceHigh":0.4},
  "gemini-2.0-flash": {"inputPrice":0.1,"outputPrice":0.4,"cacheReadPrice":0.025},
  "gemini-2.0-flash-lite": {"inputPrice":0.075,"outputPrice":0.3},
  "gemini-2.5-computer-use-preview-10-2025": {"inputPrice":1.25,"outputPrice":10,"tierThreshold":200000,"inputPriceHigh":2.5,"outputPriceHigh":15},
  "gemini-2.5-flash": {"inputPrice":0.3,"outputPrice":2.5,"cacheReadPrice":0.03},
  "gemini-2.5-flash-image": {"inputPrice":0.3,"outputPrice":30,"cacheReadPrice":0.075},
  "gemini-2.5-flash-lite": {"inputPrice":0.1,"outputPrice":0.4,"cacheReadPrice":0.01},
  "gemini-2.5-flash-preview-tts": {"inputPrice":0.5,"outputPrice":10},
  "gemini-2.5-pro": {"inputPrice":1.25,"outputPrice":10,"cacheReadPrice":0.125,"tierThreshold":200000,"inputPriceHigh":2.5,"outputPriceHigh":15,"cacheReadPriceHigh":0.25},
  "gemini-2.5-pro-preview-tts": {"inputPrice":1,"outputPrice":20},
  "gemini-3-flash-preview": {"inputPrice":0.5,"outputPrice":3,"cacheReadPrice":0.05},
  "gemini-3-pro-image": {"inputPrice":2,"outputPrice":120},
  "gemini-3-pro-image-preview": {"inputPrice":2,"outputPrice":120},
  "gemini-3-pro-preview": {"inputPrice":2,"outputPrice":12,"cacheReadPrice":0.2,"tierThreshold":200000,"inputPriceHigh":4,"outputPriceHigh":18,"cacheReadPriceHigh":0.4},
  "gemini-3.1-flash-image": {"inputPrice":0.5,"outputPrice":60},
  "gemini-3.1-flash-image-preview": {"inputPrice":0.5,"outputPrice":60},
  "gemini-3.1-flash-lite": {"inputPrice":0.25,"outputPrice":1.5,"cacheReadPrice":0.025},
  "gemini-3.1-flash-lite-image": {"inputPrice":0.25,"outputPrice":30},
  "gemini-3.1-flash-lite-preview": {"inputPrice":0.25,"outputPrice":1.5,"cacheReadPrice":0.025},
  "gemini-3.1-flash-live-preview": {"inputPrice":0.75,"outputPrice":4.5},
  "gemini-3.1-flash-tts-preview": {"inputPrice":1,"outputPrice":20},
  "gemini-3.1-pro-preview": {"inputPrice":2,"outputPrice":12,"cacheReadPrice":0.2,"tierThreshold":200000,"inputPriceHigh":4,"outputPriceHigh":18,"cacheReadPriceHigh":0.4},
  "gemini-3.1-pro-preview-customtools": {"inputPrice":2,"outputPrice":12,"cacheReadPrice":0.2,"tierThreshold":200000,"inputPriceHigh":4,"outputPriceHigh":18,"cacheReadPriceHigh":0.4},
  "gemini-3.5-flash": {"inputPrice":1.5,"outputPrice":9,"cacheReadPrice":0.15},
  "gemini-3.5-flash-lite": {"inputPrice":0.3,"outputPrice":2.5,"cacheReadPrice":0.03},
  "gemini-3.5-live-translate-preview": {"inputPrice":3.5,"outputPrice":21},
  "gemini-3.6-flash": {"inputPrice":1.5,"outputPrice":7.5,"cacheReadPrice":0.15},
  "gemini-embedding-001": {"inputPrice":0.15,"outputPrice":0},
  "gemini-embedding-2": {"inputPrice":0.2,"outputPrice":0},
  "gemini-flash-latest": {"inputPrice":1.5,"outputPrice":9,"cacheReadPrice":0.15},
  "gemini-flash-lite-latest": {"inputPrice":0.25,"outputPrice":1.5,"cacheReadPrice":0.025},
  "gemini-omni-flash-preview": {"inputPrice":1.5,"outputPrice":17.5},
  "gemini-robotics-er-1.6-preview": {"inputPrice":1,"outputPrice":5},
  "lyria-3-clip-preview": {"inputPrice":0,"outputPrice":0},
  "lyria-3-pro-preview": {"inputPrice":0,"outputPrice":0},
} satisfies Record<string, ModelPricing>;

export const openAIModelPricing = {
  "gpt-3.5-turbo": {"inputPrice":0.5,"outputPrice":1.5,"cacheReadPrice":0},
  "gpt-4": {"inputPrice":30,"outputPrice":60},
  "gpt-4-turbo": {"inputPrice":10,"outputPrice":30},
  "gpt-4.1": {"inputPrice":2,"outputPrice":8,"cacheReadPrice":0.5},
  "gpt-4.1-mini": {"inputPrice":0.4,"outputPrice":1.6,"cacheReadPrice":0.1},
  "gpt-4.1-nano": {"inputPrice":0.1,"outputPrice":0.4,"cacheReadPrice":0.025},
  "gpt-4o": {"inputPrice":2.5,"outputPrice":10,"cacheReadPrice":1.25},
  "gpt-4o-2024-05-13": {"inputPrice":5,"outputPrice":15},
  "gpt-4o-2024-08-06": {"inputPrice":2.5,"outputPrice":10,"cacheReadPrice":1.25},
  "gpt-4o-2024-11-20": {"inputPrice":2.5,"outputPrice":10,"cacheReadPrice":1.25},
  "gpt-4o-mini": {"inputPrice":0.15,"outputPrice":0.6,"cacheReadPrice":0.075},
  "gpt-5": {"inputPrice":1.25,"outputPrice":10,"cacheReadPrice":0.125},
  "gpt-5-mini": {"inputPrice":0.25,"outputPrice":2,"cacheReadPrice":0.025},
  "gpt-5-nano": {"inputPrice":0.05,"outputPrice":0.4,"cacheReadPrice":0.005},
  "gpt-5-pro": {"inputPrice":15,"outputPrice":120},
  "gpt-5.1": {"inputPrice":1.25,"outputPrice":10,"cacheReadPrice":0.125},
  "gpt-5.2": {"inputPrice":1.75,"outputPrice":14,"cacheReadPrice":0.175},
  "gpt-5.2-chat-latest": {"inputPrice":1.75,"outputPrice":14,"cacheReadPrice":0.175},
  "gpt-5.2-pro": {"inputPrice":21,"outputPrice":168},
  "gpt-5.3-chat-latest": {"inputPrice":1.75,"outputPrice":14,"cacheReadPrice":0.175},
  "gpt-5.3-codex": {"inputPrice":1.75,"outputPrice":14,"cacheReadPrice":0.175},
  "gpt-5.3-codex-spark": {"inputPrice":1.75,"outputPrice":14,"cacheReadPrice":0.175},
  "gpt-5.4": {"inputPrice":2.5,"outputPrice":15,"cacheReadPrice":0.25,"tierThreshold":272000,"inputPriceHigh":5,"outputPriceHigh":22.5,"cacheReadPriceHigh":0.5},
  "gpt-5.4-mini": {"inputPrice":0.75,"outputPrice":4.5,"cacheReadPrice":0.075},
  "gpt-5.4-nano": {"inputPrice":0.2,"outputPrice":1.25,"cacheReadPrice":0.02},
  "gpt-5.4-pro": {"inputPrice":30,"outputPrice":180,"tierThreshold":272000,"inputPriceHigh":60,"outputPriceHigh":270},
  "gpt-5.5": {"inputPrice":5,"outputPrice":30,"cacheReadPrice":0.5,"tierThreshold":272000,"inputPriceHigh":10,"outputPriceHigh":45,"cacheReadPriceHigh":1},
  "gpt-5.5-pro": {"inputPrice":30,"outputPrice":180,"tierThreshold":272000,"inputPriceHigh":60,"outputPriceHigh":270},
  "gpt-5.6": {"inputPrice":5,"outputPrice":30,"cacheReadPrice":0.5,"cacheWritePrice":6.25,"tierThreshold":272000,"inputPriceHigh":10,"outputPriceHigh":45,"cacheReadPriceHigh":1,"cacheWritePriceHigh":12.5},
  "gpt-5.6-luna": {"inputPrice":0.2,"outputPrice":1.2,"cacheReadPrice":0.02,"cacheWritePrice":0.25,"tierThreshold":272000,"inputPriceHigh":0.4,"outputPriceHigh":1.8,"cacheReadPriceHigh":0.04,"cacheWritePriceHigh":0.5},
  "gpt-5.6-sol": {"inputPrice":5,"outputPrice":30,"cacheReadPrice":0.5,"cacheWritePrice":6.25,"tierThreshold":272000,"inputPriceHigh":10,"outputPriceHigh":45,"cacheReadPriceHigh":1,"cacheWritePriceHigh":12.5},
  "gpt-5.6-terra": {"inputPrice":2,"outputPrice":12,"cacheReadPrice":0.2,"cacheWritePrice":2.5,"tierThreshold":272000,"inputPriceHigh":4,"outputPriceHigh":18,"cacheReadPriceHigh":0.4,"cacheWritePriceHigh":5},
  "gpt-image-2": {"inputPrice":5,"outputPrice":30,"cacheReadPrice":1.25},
  "gpt-realtime-2.1": {"inputPrice":4,"outputPrice":24,"cacheReadPrice":0.4},
  "o1": {"inputPrice":15,"outputPrice":60,"cacheReadPrice":7.5},
  "o1-pro": {"inputPrice":150,"outputPrice":600},
  "o3": {"inputPrice":2,"outputPrice":8,"cacheReadPrice":0.5},
  "o3-mini": {"inputPrice":1.1,"outputPrice":4.4,"cacheReadPrice":0.55},
  "o3-pro": {"inputPrice":20,"outputPrice":80},
  "o4-mini": {"inputPrice":1.1,"outputPrice":4.4,"cacheReadPrice":0.275},
  "text-embedding-3-large": {"inputPrice":0.13,"outputPrice":0},
  "text-embedding-3-small": {"inputPrice":0.02,"outputPrice":0},
  "text-embedding-ada-002": {"inputPrice":0.1,"outputPrice":0},
} satisfies Record<string, ModelPricing>;

export const claudeModelPricing = {
  "claude-fable-5": {"inputPrice":10,"outputPrice":50,"cacheReadPrice":1,"cacheWritePrice":12.5},
  "claude-haiku-4-5": {"inputPrice":1,"outputPrice":5,"cacheReadPrice":0.1,"cacheWritePrice":1.25},
  "claude-haiku-4-5-20251001": {"inputPrice":1,"outputPrice":5,"cacheReadPrice":0.1,"cacheWritePrice":1.25},
  "claude-opus-4-1": {"inputPrice":15,"outputPrice":75,"cacheReadPrice":1.5,"cacheWritePrice":18.75},
  "claude-opus-4-1-20250805": {"inputPrice":15,"outputPrice":75,"cacheReadPrice":1.5,"cacheWritePrice":18.75},
  "claude-opus-4-5": {"inputPrice":5,"outputPrice":25,"cacheReadPrice":0.5,"cacheWritePrice":6.25},
  "claude-opus-4-5-20251101": {"inputPrice":5,"outputPrice":25,"cacheReadPrice":0.5,"cacheWritePrice":6.25},
  "claude-opus-4-6": {"inputPrice":5,"outputPrice":25,"cacheReadPrice":0.5,"cacheWritePrice":6.25},
  "claude-opus-4-7": {"inputPrice":5,"outputPrice":25,"cacheReadPrice":0.5,"cacheWritePrice":6.25},
  "claude-opus-4-8": {"inputPrice":5,"outputPrice":25,"cacheReadPrice":0.5,"cacheWritePrice":6.25},
  "claude-opus-5": {"inputPrice":5,"outputPrice":25,"cacheReadPrice":0.5,"cacheWritePrice":6.25},
  "claude-sonnet-4-5": {"inputPrice":3,"outputPrice":15,"cacheReadPrice":0.3,"cacheWritePrice":3.75},
  "claude-sonnet-4-5-20250929": {"inputPrice":3,"outputPrice":15,"cacheReadPrice":0.3,"cacheWritePrice":3.75},
  "claude-sonnet-4-6": {"inputPrice":3,"outputPrice":15,"cacheReadPrice":0.3,"cacheWritePrice":3.75},
  "claude-sonnet-5": {"inputPrice":2,"outputPrice":10,"cacheReadPrice":0.2,"cacheWritePrice":2.5},
} satisfies Record<string, ModelPricing>;

export const xAIModelPricing = {
  "grok-4.20-0309-non-reasoning": {"inputPrice":1.25,"outputPrice":2.5,"cacheReadPrice":0.2,"tierThreshold":200000,"inputPriceHigh":2.5,"outputPriceHigh":5,"cacheReadPriceHigh":0.4},
  "grok-4.20-0309-reasoning": {"inputPrice":1.25,"outputPrice":2.5,"cacheReadPrice":0.2,"tierThreshold":200000,"inputPriceHigh":2.5,"outputPriceHigh":5,"cacheReadPriceHigh":0.4},
  "grok-4.20-multi-agent-0309": {"inputPrice":1.25,"outputPrice":2.5,"cacheReadPrice":0.2,"tierThreshold":200000,"inputPriceHigh":2.5,"outputPriceHigh":5,"cacheReadPriceHigh":0.4},
  "grok-4.3": {"inputPrice":1.25,"outputPrice":2.5,"cacheReadPrice":0.2,"tierThreshold":200000,"inputPriceHigh":2.5,"outputPriceHigh":5,"cacheReadPriceHigh":0.4},
  "grok-4.5": {"inputPrice":2,"outputPrice":6,"cacheReadPrice":0.3,"tierThreshold":200000,"inputPriceHigh":4,"outputPriceHigh":12,"cacheReadPriceHigh":0.6},
  "grok-build-0.1": {"inputPrice":1,"outputPrice":2,"cacheReadPrice":0.2,"tierThreshold":200000,"inputPriceHigh":2,"outputPriceHigh":4,"cacheReadPriceHigh":0.4},
} satisfies Record<string, ModelPricing>;
